// SPDX-License-Identifier: LGPL-3.0-or-later
#pragma once

enum class OperationalModelType {
    COLLISION_FREE_SPEED,
    COLLISION_FREE_SPEED_V2,
    COLLISION_FREE_SPEED_V3,
    GENERALIZED_CENTRIFUGAL_FORCE,
    ANTICIPATION_VELOCITY_MODEL,
    SOCIAL_FORCE,
    WARP_DRIVER,
    USER_DEFINED
};
